#!/usr/bin/env bash
#Displays content of current directory
for file in *; do
    # Check if the file is not hidden and has a dash in its name
    if [[ ! "$file" == .* && "$file" == *-* ]]; then
        # Extract the part of the name after the first dash
        trimmed_name=$(echo "$file" | cut -d '-' -f 2-)
        # Print the trimmed name
        echo "$trimmed_name"
    fi
done

